name: Deploy to AKS Cluster

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions.setup-java@v1
      with: 
        java-version: 17

    - name: Build java project with Maven
      run: mvn -B package --file pom.xml
    
